<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-E9GH2O5" failures="0" tests="8" name="com.restassured.testcases.TC004_put_Empolyees_Record" time="5.793" errors="1" timestamp="01 Aug 2022 13:42:10 GMT" skipped="0">
  <testcase classname="com.restassured.testcases.TC004_put_Empolyees_Record" name="checkStatusCode" time="0.002"/>
  <testcase classname="com.restassured.testcases.TC004_put_Empolyees_Record" name="checkResponseBody" time="0.001">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.restassured.testcases.TC004_put_Empolyees_Record.checkResponseBody(TC004_put_Empolyees_Record.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
    </error>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.restassured.testcases.TC004_put_Empolyees_Record" name="checkcontent_Length" time="0.000"/>
  <testcase classname="com.restassured.testcases.TC004_put_Empolyees_Record" name="checkContent_Type" time="0.006"/>
  <testcase classname="com.restassured.testcases.TC004_put_Empolyees_Record" name="checkresponceTime" time="0.001"/>
  <testcase classname="com.restassured.testcases.TC004_put_Empolyees_Record" name="checkStatusLine" time="0.001"/>
  <testcase classname="com.restassured.testcases.TC004_put_Empolyees_Record" name="UpdateEmployee" time="5.781"/>
  <testcase classname="com.restassured.testcases.TC004_put_Empolyees_Record" name="checkServer_Type" time="0.001"/>
</testsuite> <!-- com.restassured.testcases.TC004_put_Empolyees_Record -->
